name: macOS Remote Terminal

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Start Interactive Termius Tunnel
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false
